### ISSUE TITLE
SNOPT error

### ISSUE THREAD

**Issue by michK** [madebr/pyOpt#6]
**UPDATE: In retrospect I realized this might not be an official fork and is perhaps not the correct place to ask this. Please let me know if that is the case.**

Good day,

I am getting an error when trying to solve a basic test case on a Ubuntu 18.04 machine.

I followed the following steps to build pyOpt with SNOPT:

```
cd ~/pyOpt
cp ~/snopt7/src/*.f pyOpt/pySNOPT/source/
rm pyOpt/pySNOPT/source/snopth.f
python setup.py build
```
Initially, the build failed, and then following [these](https://github.com/mdolab/pyoptsparse/issues/20#event-2174818772) instructions for pyoptsparse I delete the `snopth.f` file, after which the build seemed to work.

First I tested this problem with the SLSQP solver, which worked:

```
import pyOpt

def objfunc(x):
    f = -x[0] * x[1] * x[2]
    g = [0.0] * 2
    g[0] = x[0] + 2. * x[1] + 2. * x[2] - 72.0
    g[1] = -x[0] - 2. * x[1] - 2. * x[2]
    fail = 0
    return f, g, fail

opt_prob = pyOpt.Optimization('TP37 Constrained Problem', objfunc)
opt_prob.addObj('f')
opt_prob.addVar('x1', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addVar('x2', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addVar('x3', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addConGroup('g', 2, 'i')
print(opt_prob)
slsqp = pyOpt.SLSQP()
slsqp.setOption('IPRINT', -1)
[fstr, xstr, inform] = slsqp(opt_prob)
print(opt_prob.solution(0))
```
Then I tested essentially the same problem with SNOPT:

```
import pyOpt

def objfunc(x):

    f = -x[0] * x[1] * x[2]
    g = [0.0] * 2
    g[0] = x[0] + 2. * x[1] + 2. * x[2] - 72.0
    g[1] = -x[0] - 2. * x[1] - 2. * x[2]
    fail = 0
    return f, g, fail

opt_prob = pyOpt.Optimization('TP37 Constrained Problem', objfunc)
opt_prob.addObj('f')
opt_prob.addVar('x1', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addVar('x2', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addVar('x3', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addConGroup('g', 2, 'i')
print(opt_prob)
snopt = pyOpt.SNOPT()
[fstr, xstr, inform] = snopt(opt_prob)
print(opt_prob.solution(0))
```

But this failed with:

`OSError: Failed to properly open SNOPT_print.out, ierror = 5002`

I am not sure if something went wrong with the build, or maybe with the problem setup.

I would appreciate any help with this, thanks!

**Comment by madebr** [comment]
The SNOPT fortran sources were never in the pyopt release.
Probably because of licensing.

See http://www.sbsi-sol-optimize.com/asp/sol_product_snopt.htm

**Comment by JohnDN90** [comment]
I encountered the same error in my own version of pyOpt which I modified for use with Python 3.

The issue isn't with either the SNOPT sources or the pyOpt f2py interface, but rather with the way Python 3 handles strings.  The f2py interface to SNOPT expects a byte string (which is the default type of string in Python 2), but Python 3 is passing it a unicode string (the default type in Python 3). The fix was pretty easy.

On [line 510 of pySNOPT.py ](https://github.com/madebr/pyOpt/blob/master/pyOpt/pySNOPT/pySNOPT.py#L510), make the following modification:

`PrintFile = self.options['Print file'][1] # Original`
`PrintFile = self.options['Print file'][1].encode('utf-8') # New`

On [line 514 of pySNOPT.py](https://github.com/madebr/pyOpt/blob/master/pyOpt/pySNOPT/pySNOPT.py#L514), make the following modification:

`ierror = snopt.openunit(iPrint, numpy.array(PrintFile), numpy.array('new'), numpy.array('sequential')) # Original`
`ierror = snopt.openunit(iPrint, numpy.array(PrintFile), numpy.array(b'new'), numpy.array(b'sequential')) # New`

On [line 521 of pySNOPT.py](https://github.com/madebr/pyOpt/blob/master/pyOpt/pySNOPT/pySNOPT.py#L521), make the following modification:

`SummFile = self.options['Summary file'][1] # Original`
`SummFile = self.options['Summary file'][1].encode('utf-8') # New`

On [line 525 of pySNOPT.py](https://github.com/madebr/pyOpt/blob/master/pyOpt/pySNOPT/pySNOPT.py#L525), make the following modification:

`ierror = snopt.openunit(iSumm, numpy.array(SummFile), numpy.array('new'), numpy.array('sequential'))`
`ierror = snopt.openunit(iSumm, numpy.array(SummFile), numpy.array(b'new'), numpy.array(b'sequential'))`

These four modifications corrected the issues in my own modified version of pyOpt. I tested it by solving the tp037.py example problem using SNOPT.  I haven't tested it on the version in this repository, but I imagine the fix should be the same.

**Comment by madebr** [comment]
@JohnDN90 
Would you be so nice and create a pr with your fixes?
I don't own a snopt license so I can't verify.
